### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by neighborhood999** [neighborhood999/redux-saga#2]
## 翻譯進度
- [x] Read Me
- [x] 介紹
  - [x] 新手教學
  - [x] Saga 的背景
- [x] 基本概念
  - [x] 使用 Saga Helpers
  - [x] 宣告 Effect
  - [x] Dispatch action
  - [x] 錯誤處理
  - [x] 一個常見的抽象概念：Effect
- [x] 進階概念
  - [x] Pull 未來的 action
  - [x] 非阻塞式的呼叫 
  - [x] 同時執行多個任務
  - [x] 在多個 Effect 之間啟動一個 race
  - [x] 使用 yield\* 對 Saga 做排序
  - [x] 組合 Saga
  - [x] 任務取消
  - [x] 常見的併發模式
  - [x] Saga 測試的範例
  - [x] 連結 Saga 到外部的輸入和輸出
  - [x] 使用 Channel
- [x] Recipes
- [x] 外部資源
- [x] 疑難排解
- [x] 術語表
- [x] API 參考
